### ISSUE TITLE
Several errors

### ISSUE THREAD

**Issue by selimanac** [JamalK/Swift-String-Tools#7]
StringExtensions.swift:38:22: 'String' is not convertible to 'Range<I>'
StringExtensions.swift:229:22: Use of unresolved identifier 'Set'
StringExtensions.swift:204:22: Use of unresolved identifier 'Set'

**Comment by JamalK** [comment]
Make sure you're using Swift 1.2 or Xcode-Beta5 since Set was introduced in it, otherwise, you can use NSSet, and return allObjects

**Comment by selimanac** [comment]
Thanks a lot. But i'm not a beta build fan. So i'll wait.
